/**
 * Stub generator — produces a TypeScript module the script imports as
 * `memi_tools`. Each tool in the per-call allowlist becomes a typed
 * async function that round-trips a request to the parent over the
 * Unix socket and returns the result.
 *
 * Usage from parent:
 *   const stub = generateMemiToolsStub({
 *     socketEnvVar: "MEMI_TOOLS_SOCKET",
 *     tools: [
 *       { name: "Read",  argsType: "{ path: string }",        resultType: "string" },
 *       { name: "Write", argsType: "{ path: string; content: string }", resultType: "void" },
 *       { name: "Bash",  argsType: "{ command: string; timeoutMs?: number }",
 *                        resultType: "{ stdout: string; stderr: string; code: number }" },
 *     ],
 *   });
 *   await writeFile("/tmp/memi_tools.ts", stub);
 *
 * Then the user script:
 *   import { Read, Write, Bash, log, exit } from "./memi_tools.ts";
 *   const files = await Bash({ command: "find . -name '*.ts'" });
 *   for (const f of files.stdout.split("\n").filter(Boolean)) {
 *     log("info", `processing ${f}`);
 *     const content = await Read({ path: f });
 *     await Write({ path: f, content: content.toUpperCase() });
 *   }
 *   exit(true, { fileCount: files.stdout.split("\n").length });
 *
 * The stub uses a single Unix-socket connection (created lazily on first
 * call) and multiplexes tool calls with monotonic ids. log() fires a
 * one-way log message; exit() sends the final result and closes the
 * socket. Calling exit() more than once is a no-op.
 */

export interface StubToolSpec {
  /** Tool name as exported on the stub module. Must be a valid TS identifier. */
  readonly name: string;
  /** TypeScript type for the args object. */
  readonly argsType: string;
  /** TypeScript type for the result. */
  readonly resultType: string;
  /** Optional one-line doc rendered as a TSDoc comment above the function. */
  readonly description?: string;
}

export interface StubGeneratorOptions {
  /** Env var the script reads to find the socket path. */
  readonly socketEnvVar: string;
  /** Tool surface for the script. */
  readonly tools: ReadonlyArray<StubToolSpec>;
  /** Optional file header comment. */
  readonly header?: string;
}

const VALID_IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export function generateMemiToolsStub(options: StubGeneratorOptions): string {
  for (const tool of options.tools) {
    if (!VALID_IDENT.test(tool.name)) {
      throw new Error(`generateMemiToolsStub: tool name "${tool.name}" is not a valid TS identifier`);
    }
  }

  const header = options.header
    ?? `// Auto-generated by Mémoire execute_code. Do not edit — regenerated per call.\n// Socket: process.env.${options.socketEnvVar}\n`;

  const tools = options.tools
    .map((tool) => {
      const doc = tool.description
        ? `/** ${tool.description.replace(/\*\//g, "* /")} */\n`
        : "";
      return `${doc}export async function ${tool.name}(args: ${tool.argsType}): Promise<${tool.resultType}> {\n  return rpc("${tool.name}", args) as Promise<${tool.resultType}>;\n}\n`;
    })
    .join("\n");

  return `${header}
import { connect, type Socket } from "node:net";

const SOCKET_PATH = process.env["${options.socketEnvVar}"];
if (!SOCKET_PATH) {
  console.error("[memi_tools] missing env var ${options.socketEnvVar}; cannot reach parent");
  process.exit(1);
}

let socket: Socket | null = null;
let connectPromise: Promise<Socket> | null = null;
let nextId = 1;
const pending = new Map<number, { resolve: (value: unknown) => void; reject: (error: Error) => void }>();
let exited = false;
let buffer = "";

function ensureConnection(): Promise<Socket> {
  if (socket) return Promise.resolve(socket);
  if (connectPromise) return connectPromise;
  connectPromise = new Promise<Socket>((resolve, reject) => {
    const s = connect(SOCKET_PATH);
    s.once("connect", () => {
      socket = s;
      s.on("data", (chunk) => {
        buffer += chunk.toString("utf-8");
        let nl: number;
        while ((nl = buffer.indexOf("\\n")) !== -1) {
          const line = buffer.slice(0, nl);
          buffer = buffer.slice(nl + 1);
          if (!line.trim()) continue;
          try {
            const msg = JSON.parse(line) as { id: number; ok: boolean; result?: unknown; error?: string };
            const handler = pending.get(msg.id);
            if (!handler) continue;
            pending.delete(msg.id);
            if (msg.ok) handler.resolve(msg.result);
            else handler.reject(new Error(msg.error || "tool call failed"));
          } catch {
            // skip malformed
          }
        }
      });
      s.on("close", () => {
        for (const handler of pending.values()) {
          handler.reject(new Error("parent closed connection"));
        }
        pending.clear();
      });
      resolve(s);
    });
    s.once("error", reject);
  });
  return connectPromise;
}

async function rpc(tool: string, args: unknown): Promise<unknown> {
  const s = await ensureConnection();
  const id = nextId++;
  return new Promise<unknown>((resolve, reject) => {
    pending.set(id, { resolve, reject });
    s.write(JSON.stringify({ id, op: "tool", tool, args }) + "\\n");
  });
}

/** Send a one-way log line to the parent. Visible in the agent's diagnostic stream. */
export async function log(level: "info" | "warn" | "error", message: string, data?: unknown): Promise<void> {
  const s = await ensureConnection();
  const id = nextId++;
  s.write(JSON.stringify({ id, op: "log", level, message, data }) + "\\n");
}

/** Tell the parent the script is done. Calling more than once is a no-op. */
export async function exit(ok: boolean, result?: unknown, error?: string): Promise<void> {
  if (exited) return;
  exited = true;
  const s = await ensureConnection();
  const id = nextId++;
  s.write(JSON.stringify({ id, op: "exit", ok, result, error }) + "\\n");
  await new Promise<void>((resolve) => setTimeout(resolve, 10));
  s.end();
}

${tools}`;
}
